name: Git Crypt Unlock
description: Installs git-crypt and unlocks the repository
inputs:
  GIT_CRYPT_KEY:
    description: The git-crypt key
    required: true
runs:
  using: "composite"
  steps:

    # https://github.com/marketplace/actions/github-action-to-unlock-git-crypt-secrets
    # git-crypt export-key ./tmp-key && cat ./tmp-key | base64 | pbcopy && rm ./tmp-key
    # The git-crypt key needs to be exported  and base64 encoded
    # After that it should be added as a repository secret with the name GIT_CRYPT_KEY
    - name: Install git-crypt
      run: |
        if which git-crypt >/dev/null; then
          echo "git-crypt installed"
        else
          openssl version
          cpp --version
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            git clone https://github.com/AGWA/git-crypt.git
            cd git-crypt && CXXFLAGS='-DOPENSSL_API_COMPAT=0x30000000L' make && CXXFLAGS='-DOPENSSL_API_COMPAT=0x30000000L' make install PREFIX=/opt/project
            echo "/opt/project/bin" >> $GITHUB_PATH
          else
            brew install git-crypt
          fi
        fi
      shell: bash

    - name: Unlock git-crypt
      run: |
        echo "${{ inputs.GIT_CRYPT_KEY }}" | base64  -d > ./git-crypt-key
        git-crypt unlock ./git-crypt-key && echo "success"
        rm ./git-crypt-key
      shell: bash
